// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WireMock.Server;

#nullable disable

namespace WireMock.Migrations
{
    [DbContext(typeof(WireMockServerContext))]
    [Migration("20240621090815_UpdatedModel")]
    partial class UpdatedModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WireMock.Server.WireMockServerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxyUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaveMapping")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaveMappingForStatusCodePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaveMappingToFile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartAdminInterface")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Urls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WireMockServerModel");
                });
#pragma warning restore 612, 618
        }
    }
}
