// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WireMock.Server;

#nullable disable

namespace WireMock.Migrations
{
    [DbContext(typeof(WireMockServerContext))]
    partial class WireMockServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WireMock.Server.WireMockServerMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Raw")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WireMockServerModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("WireMockServerModelId");

                    b.ToTable("WireMockServerMapping");
                });

            modelBuilder.Entity("WireMock.Server.WireMockServerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaveMapping")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaveMappingForStatusCodePattern")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaveMappingToFile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartAdminInterface")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WireMockServerModel");
                });

            modelBuilder.Entity("WireMock.Server.WireMockServerMapping", b =>
                {
                    b.HasOne("WireMock.Server.WireMockServerModel", null)
                        .WithMany("Mappings")
                        .HasForeignKey("WireMockServerModelId");
                });

            modelBuilder.Entity("WireMock.Server.WireMockServerModel", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
