name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - refactor/Make-Analyzer-happy-again

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@999cd8704bc23bf11c8c894b573f6e92e949b860
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --baseline,qodana.sarif.json