name: SonarCloud

on: [push]

jobs:
  sonar:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: |
        dotnet tool install --global dotnet-coverage
        
        [jdk setup]
        
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"vanUbor_Wiremock" /o:"vanubor" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        dotnet build --configuration Release
        dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"